import { useNavigate } from 'react-router';
import { Paper, Button, Group, Stack, TextInput, Select, NumberInput } from '@mantine/core';
import { DatePickerInput } from '@mantine/dates';
import { useForm } from '@mantine/form';
import { notifications } from '@mantine/notifications';
import { IconCheck, IconX } from '@tabler/icons-react';
import { PageHeader } from '../../../components/ui/PageHeader';
import { useCreateArReceipt } from '../../../hooks/useArReceipt';
import type { ArReceipt } from '../../../types/models';

export default function ArReceiptCreate() {
  const navigate = useNavigate();
  const createMutation = useCreateArReceipt();

  const form = useForm({
    initialValues: {
      RcptDate: new Date(),
      ProfileId: 0,
      RcptAmount: 0,
      CurCode: 'THB',
      CurRate: 1,
      Description: '',
      BankCode: '',
    },
    validate: {
      ProfileId: (value) => (value <= 0 ? 'Profile is required' : null),
      RcptAmount: (value) => (value <= 0 ? 'Amount must be greater than 0' : null),
    },
  });

  const handleSubmit = async (values: typeof form.values) => {
    try {
      const payload: Omit<ArReceipt, 'ArRcptSeq'> = {
        ...values,
        RcptDate: values.RcptDate.toISOString().split('T')[0],
        RcptNo: '', // Will be generated by backend
        ProfileCode: '', // Will be populated by backend based on ProfileId
        ProfileName: '', // Will be populated by backend based on ProfileId
        RcptAmountBase: values.RcptAmount * values.CurRate,
        Status: 'Draft',
        Detail: [],
        UserModified: '', // Will be set by backend
      };
      await createMutation.mutateAsync(payload);
      notifications.show({
        title: 'Success',
        message: 'Receipt created successfully',
        color: 'green',
        icon: <IconCheck size={16} />,
      });
      navigate('/ar/receipt');
    } catch {
      notifications.show({
        title: 'Error',
        message: 'Failed to create receipt',
        color: 'red',
        icon: <IconX size={16} />,
      });
    }
  };

  return (
    <Stack gap="md">
      <PageHeader
        title="Create AR Receipt"
        breadcrumbs={[
          { label: 'AR', href: '/ar' },
          { label: 'Receipts', href: '/ar/receipt' },
          { label: 'Create' },
        ]}
      />

      <Paper withBorder p="md">
        <form onSubmit={form.onSubmit(handleSubmit)}>
          <Stack gap="md">
            <Group grow>
              <DatePickerInput
                label="Receipt Date"
                required
                {...form.getInputProps('RcptDate')}
              />
              <Select
                label="Payment Method"
                data={[
                  { value: '', label: 'Cash' },
                  { value: 'CHQ', label: 'Cheque' },
                  { value: 'TRF', label: 'Bank Transfer' },
                  { value: 'CC', label: 'Credit Card' },
                ]}
                {...form.getInputProps('BankCode')}
              />
            </Group>

            <NumberInput
              label="Profile ID"
              placeholder="Enter profile ID"
              required
              min={1}
              {...form.getInputProps('ProfileId')}
            />

            <Group grow>
              <NumberInput
                label="Amount"
                required
                min={0}
                decimalScale={2}
                {...form.getInputProps('RcptAmount')}
              />
              <TextInput
                label="Currency"
                {...form.getInputProps('CurCode')}
              />
              <NumberInput
                label="Exchange Rate"
                decimalScale={4}
                {...form.getInputProps('CurRate')}
              />
            </Group>

            <TextInput
              label="Description"
              placeholder="Enter description"
              {...form.getInputProps('Description')}
            />

            <Group justify="flex-end" mt="md">
              <Button variant="light" onClick={() => navigate('/ar/receipt')}>
                Cancel
              </Button>
              <Button type="submit" loading={createMutation.isPending}>
                Create Receipt
              </Button>
            </Group>
          </Stack>
        </form>
      </Paper>
    </Stack>
  );
}
